name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        Please search existing issues to avoid duplicates and check the roadmap in the README.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the documentation and this feature is not already available
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - SQLMesh Integration
        - Dagster Assets
        - Asset Checks/Audits
        - Scheduling
        - Translation/Mapping
        - Performance
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: "Currently, users cannot... which makes it difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've considered... but it doesn't work because..."

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      render: python
      placeholder: |
        # Example of how the new feature would work
        from dg_sqlmesh import ...
        
        # New feature usage
        ...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Areas
      description: What areas would this feature affect? (Select all that apply)
      options:
        - label: Breaking changes to existing API
        - label: New dependencies required
        - label: Performance implications
        - label: Documentation updates needed
        - label: Additional testing required

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links about the feature request
